const cfg=window.FANVERSE_SUPABASE||{};
const EVENT_SLUG=cfg.eventSlug||'season-01';
const TEAM_NAMES={crush:'CRUSH',manifest:'MANIFEST',aura:'AURA',karm6:'KARM6',mantra:'MANTRA',radikal:'RADİKAL',perma:'PERMA'};
const TEAM_COLORS={crush:'#ff4b9b',manifest:'#4ba8ff',aura:'#9c6bff',karm6:'#ff7b38',mantra:'#ffcf42',radikal:'#ee4054',perma:'#4ce3a4'};
const sb=(cfg.url&&cfg.publishableKey&&window.supabase?.createClient)?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
let mode='global',team='crush',page=1,total=0;const pageSize=25;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const el=$('leaderToast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2500)}
function rowHtml(r){const color=TEAM_COLORS[r.team_id]||'#94a3b8';return `<article class="rank-row"><span class="rank-num">${Number(r.rank||0)}</span><div class="rank-user"><div class="rank-name"><i style="background:${color}"></i><strong>${esc(r.username||'fan')}</strong><span>${TEAM_NAMES[r.team_id]||esc(r.team_id||'—')}</span></div><small>${Number(r.placements||0).toLocaleString('tr-TR')} piksel · ${Number(r.enemy_pixels_taken||0).toLocaleString('tr-TR')} rakip piksel · ${Number(r.unique_provinces||0)} il</small></div><strong class="rank-score">${Number(r.score||0).toLocaleString('tr-TR')}<small>puan</small></strong></article>`}
function updateModeUi(){ $('globalModeBtn').classList.toggle('active',mode==='global');$('teamModeBtn').classList.toggle('active',mode==='team');$('teamFilterWrap').classList.toggle('hidden',mode!=='team');$('rankingKicker').textContent=mode==='global'?'GENEL SIRALAMA':`${TEAM_NAMES[team]} İÇ SIRALAMA`;$('rankingTitle').textContent=mode==='global'?'Tüm oyuncular':`${TEAM_NAMES[team]} oyuncuları`; }
async function load(){updateModeUi();if(!sb){$('rankingList').innerHTML='<div class="empty">Supabase yapılandırılmadı.</div>';return;}$('rankingList').innerHTML='<div class="empty">Sıralama yükleniyor…</div>';const {data,error}=await sb.rpc('public_player_leaderboard',{p_event_slug:EVENT_SLUG,p_team_id:mode==='team'?team:null,p_page:page,p_page_size:pageSize});if(error){console.error(error);$('rankingList').innerHTML='<div class="empty">Liderlik RPC bulunamadı. supabase-v20.sql migrationını çalıştır.</div>';return;}const rows=data||[];total=Number(rows[0]?.total_count||0);$('rankingCount').textContent=`${total.toLocaleString('tr-TR')} oyuncu`;$('rankingList').innerHTML=rows.map(rowHtml).join('')||'<div class="empty">Henüz oyuncu yok.</div>';const pages=Math.max(1,Math.ceil(total/pageSize));if(page>pages){page=pages;return load();}$('pageText').textContent=`${page} / ${pages}`;$('prevPageBtn').disabled=page<=1;$('nextPageBtn').disabled=page>=pages;}
$('globalModeBtn').onclick=()=>{mode='global';page=1;load()};$('teamModeBtn').onclick=()=>{mode='team';page=1;load()};$('teamFilter').onchange=e=>{team=e.target.value;page=1;load()};$('prevPageBtn').onclick=()=>{if(page>1){page--;load()}};$('nextPageBtn').onclick=()=>{if(page<Math.ceil(total/pageSize)){page++;load()}};
const params=new URLSearchParams(location.search);mode=params.get('mode')==='team'?'team':'global';team=TEAM_NAMES[params.get('team')]?params.get('team'):'crush';$('teamFilter').value=team;load();
